version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      PORT: "8008"
      REMOTE_PAGES_REPO: "git@github.com:thomd/notebook-pages.git"
      LOCAL_PAGES_REPO: "/data"
    ports:
      - '8008:8008'
    volumes:
      - "~/.notebook:/data"
    restart: "no"
    secrets:
      - notebook_ssh_key
secrets:
  notebook_ssh_key:
    file: ~/.ssh/notebook
