services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      REMOTE_PAGES_REPO: ${REMOTE_PAGES_REPO}
      REMOTE_REPO_USERNAME: ${REMOTE_REPO_USERNAME}
      REMOTE_REPO_EMAIL: ${REMOTE_REPO_EMAIL}
      LOCAL_PAGES_REPO: "/data"
      PAGES_DIR: "/data/pages"
    ports:
      - '8000:8000'
    volumes:
      - "~/.notebook:/data"
    restart: "no"
    secrets:
      - notebook_ssh_key
secrets:
  notebook_ssh_key:
    file: ~/.ssh/notebook
